# GitHub CI build pipeline
name: anypython CI build

on:
  pull_request:
    branches:
      - master
      - main
jobs:
  build:
    runs-on:  ${{ matrix.os }} 
    env:
      PYTHONIOENCODING: "utf8"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version:  ${{ matrix.python-version }} 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run Linting
        run: |
          ruff check .
      - name: Run Tests
        run: |
          pytest tests/
